server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  application:
    name: umeet-admin-server
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
 # zipkin:
  #  base-url: http://localhost:9012

  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: D:/test
      max-file-size: 1Mb
      max-request-size: 10Mb

logging:
  level:
    com.systec.umeet.dao : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  type-aliases-package: com.systec.umeet.model
  model:
    pack: com.systec.umeet.model
  table:
    auto: update
  mapper-locations: classpath*:/mappers/**.xml
  configuration:
    mapUnderscoreToCamelCase: true
mapper:
  mappers: com.systec.umeet.utills.MyMapper
  not-empty: true
  identity: MYSQL


druid:
  url: jdbc:mysql://localhost:3306/nycloud-admin-v2?useUnicode=true&characterEncoding=utf8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: systec
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
